global:
  # Enable the use of a custom security context
  securityContext:
    enabled: true
    fsGroup: 1001  # Ensures the mounted volumes are accessible to the non-root user (1001)

primary:
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1000   # Custom non-root user ID
    fsGroup: 1001     # Group ID for file permissions

  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 1000
  persistence:
    enabled: true
    size: 10Gi  # Adjust the size as necessary
    storageClass: "retainer"  # Use retainer storage class for Retain reclaim policy

# Configure the password using the secret from Kubernetes
auth:
  existingSecret: hypha-secrets
  secretKeys:
    adminPasswordKey: POSTGRES_PASSWORD
    userPasswordKey: POSTGRES_PASSWORD
    postgresPasswordKey: POSTGRES_PASSWORD
  # Ensure database settings match
  username: hypha-admin
  database: hypha-db

