# Default values for imjoy-app-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
acmeEmail: "oeway007@gmail.com"
container: imjoy/imjoy-app-engine
certSecretName: imjoy-app-engine-tls
imjoyHostName: engine.imjoy.io
s3ConsoleHostName: s3-console.imjoy.io
# s3_endpoint_url: ""
auth0_audience: https://imjoy.eu.auth0.com/api/v2/
auth0_domain: imjoy.eu.auth0.com
jwt_secret: 352esl345IEo3kjsw3fsdf39sdfl3K23KJE#D*#4d

# s3_access_key: rootuser
# s3_secret_key: rootpass123
triton_url: "http://tritoninferenceserver.tritoninferenceserver.svc.cluster.local:8000"
# port: 9520
# productionMode: false # using `letsencrypt-prod` if set to true
service:
  name: hypha
  type: ClusterIP
  # sessionAffinity: None
  # sessionAffinityConfig: {}
  # clusterIP:
  port: 9520
  # nodePort:
  # loadBalancerIP:
  # loadBalancerSourceRanges:
  annotations: {}
  # foo.io/bar: "true"

cert-manager:
  enabled: false

ingress:
  enabled: false

ingress-nginx:
  enabled: false
  rbac:
    create: true
  defaultBackend:
    enabled: true
  controller:
    ingressClassResource:
      default: true

docker-registry:
  enabled: false
  # storage: s3
  # secrets:
  #   s3:
  #     accessKey: imjoy
  #     secretKey: Nbj2cbcUDGGy7QNS8RjCwMrNRXrp2Ms7UXeF
  # s3:
  #   region: EU
  #   regionEndpoint: http://minio-s3:9000
  #   bucket: docker-registry
  #   secure: false
  # service:
  #   port: 5000
  #   nodePort: 31822 # only valid when using NodePort

minio:
  enabled: true
  rootUser: rootuser
  rootPassword: rootpass123
  # accessKey: ""
  # secretKey: ""
  replicas: 4
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    path: /s3(/|$)(.*)
    hosts:
      - imjoy.duckdns.org
  resources:
    requests:
      memory: 2Gi
  persistence:
    size: 10Gi

tritoninfereceserver-hypha:
  enabled: true
  replicaCount: 1
  image:
    imageName: nvcr.io/nvidia/tritonserver:21.10-py3
    pullPolicy: IfNotPresent
    # modelRepositoryPath: s3://imjoy-s3.pasteur.fr:80/model-repository
    modelRepositoryPath: /model-repository
    modelSnapshotsPath: /model-snapshots
    numGpus: 1
    s3Endpoint: https://uk1s3.embassy.ebi.ac.cuk
    s3Bucket: s3://model-repository/
  ingress:
    enabled: false

  # service:
  #   type: ClusterIP