apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hypha-server.fullname" . }}-data-pvc
  labels:
    {{- include "hypha-server.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
