apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hypha-server-kit.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hypha-server-kit.labels" . | nindent 4 }}
data:
  # Database configuration
  {{- if .Values.postgresql.enabled }}
  database-uri: "postgresql+asyncpg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  {{- else }}
  database-uri: "sqlite+aiosqlite:////data/hypha-app-database.db"
  {{- end }}
  
  # Redis configuration
  {{- if .Values.redis.enabled }}
  {{- if .Values.redis.auth.enabled }}
  redis-uri: "redis://:{{ .Values.redis.auth.password }}@{{ .Release.Name }}-redis-master:6379/0"
  {{- else }}
  redis-uri: "redis://{{ .Release.Name }}-redis-master:6379/0"
  {{- end }}
  {{- else }}
  redis-uri: ""
  {{- end }}
  
  # S3/MinIO configuration
  {{- if .Values.minio.enabled }}
  s3-enabled: "true"
  s3-endpoint: "http://{{ .Release.Name }}-minio:9000"
  s3-endpoint-public: "http://{{ .Release.Name }}-minio:9000"
  s3-admin-type: "minio"
  s3-proxy-enabled: "true"
  {{- else }}
  s3-enabled: "false"
  s3-endpoint: ""
  s3-endpoint-public: ""
  s3-admin-type: "generic"
  s3-proxy-enabled: "false"
  {{- end }}