{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: hypha-server-kit-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "hypha-server-kit.name" . }}
    helm.sh/chart: {{ include "hypha-server-kit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- if .Values.minio.enabled }}
  S3_ACCESS_KEY: {{ .Values.minio.auth.rootUser | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.minio.auth.rootPassword | b64enc | quote }}
  {{- else if .Values.secrets.s3AccessKey }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | b64enc | quote }}
  {{- else }}
  S3_ACCESS_KEY: {{ "" | b64enc | quote }}
  S3_SECRET_KEY: {{ "" | b64enc | quote }}
  {{- end }}
{{- end }}