{{- if .Values.ingress.enabled -}}
{{- $apiVersions := .Capabilities.APIVersions -}}
{{- $serviceName := include "docker-registry.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $path := .Values.ingress.path -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hyphaserver
  namespace: hyphaserver
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
{{- if $apiVersions.Has "networking.k8s.io/v1" }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $path }}
{{- if $apiVersions.Has "networking.k8s.io/v1" }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
{{- else }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
{{- end }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: hyphaserver
#   namespace: hyphaserver
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`imjoy.duckdns.org`)
#       kind: Rule
#       services:
#         - name: hyphaserver
#           port: 80
#   tls:
#     secretName: tls-secret
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: hyphaserver
#   namespace: hyphaserver
# spec:
#   selector:
#     app: hyphaserver
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: "http"