name: Test and Publish Hypha Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'hypha/VERSION'
  pull_request:
    branches:
      - main
    paths:
      - 'hypha/VERSION'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Kubernetes cluster using KinD
      uses: helm/kind-action@v1.10.0
      with:
        version: v0.20.0

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.11.2

    - name: Create hypha namespace
      run: kubectl create namespace hypha

    - name: Package Helm chart
      run: |
        cd helm-charts
        helm package hypha-server

    - name: Install Hypha Helm chart from packaged .tgz
      run: helm install hypha-server ./helm-charts/hypha-server-*.tgz --namespace=hypha

    - name: Uninstall Hypha Helm chart
      run: helm uninstall hypha-server --namespace=hypha

    - name: Delete namespace
      run: kubectl delete namespace hypha
